##
## Programmer:    Craig Stuart Sapp <craig@ccrma.stanford.edu>
## Creation Date: Wed Nov 27 14:56:43 CET 2019
## Last Modified: Wed Nov 27 14:56:46 CET 2019
## Syntax:        GNU Makefile
## Filename:      performances/scripts/Makefile
## vim:           ts=3
##
## Description:   Makefile to download javascript programs for running
##                of the website locally.  After the scripts have been
##                downloaded, type:
##                     ./.serve-local
##                in the parent directory to run the local version of
##                the website.
##

download:
	wget https://musicbox.sapp.org/scripts/musicbox.js -O musicbox.js
	wget https://verovio-script.humdrum.org/scripts/verovio-toolkit.js -O verovio-toolkit.js

